main.py
Database changes:
ALTER TABLE `drops` ADD `source` VARCHAR(30) NULL , ADD `channel` VARCHAR(25) NULL , ADD `timestamp` BIGINT NULL ;
ALTER TABLE `waifus` ADD INDEX `rarity` (`rarity`);
=> Improve drop logging and misc fixes

LICENSE, main.py
Multiple disenchant & shorthand syntax for booster select
=> Quality of life improvements

main.py
* Make everything (well, almost everything) use user ids instead of names
* Move open boosters to the database (and make creating new ones easy, too)
* A few miscellaneous bugfixes found during the above userid refactor.
=> The big refactor for boosters and user ids

main.py
Refactor time betting to allow storing and retrieving results, and add an [experimental] payout command for admins only.
=> Bet system improvements

main.py
Do some prep work for more complex packs later
Special cards will no longer count towards hand limit
The amount of your limit you're using is now shown by !checkhand public
Properly block fair-trading special cards
=> Some tweaks that actually change UX for once

main.py
Alerts for disenchant (set to legendary+ in production) and promotion, as well as some other alerts tidyup. Removing !giveme since it has served its purpose.
=> Alert improvements

main.py
Configize price of hand upgrades, add a waifu importer command for admins
=> Sale stuff

main.py
Took out the ability to give multiple specific waifus from one token for simplicity reasons, but the rest seems worth it.
=> New redeem system for multiuse, logging and booster tokens

.gitignore, main.py
* `!bounty id points` to place
* `!bounty cancel id` to cancel
* `!bounty check id` to check current bounties
* `!bounty list` to see your own bounties
* Bounties take up a hand space each - they're a powerful but costly tool!
=> Bounty system

main.py
Event packs will still use separate weightings. This is intended to *slowly* ease out cards that aren't pulled for a while.
=> Allow for gradual weighting changes over time

main.py, website.js
Update the bot for HDN Marathon mk2 features
=> Mk2 marathon stuff

bootstrapboostertemplate.htm, bootstraphandtemplate.htm, profiletemplate.html, smartsets.htm, waifus-bootstrap.css, website.js
=> Concerning #47

main.py
Signed-off-by: Marenthyu <marenthyu@marenthyu.de>
regarding #55
=> Shorten most commonly used messages a bit

main.py
This implements the system as discussed in some detail in #tcg-trading-room-discussion - a sequence of free rewards ordered randomly for each user with some bias towards spacing out rewards considered "good".
Not to be merged yet as the concept could still use some more feedback and it will probably have merge conflicts with the "tidyup" PR anyway.
=> Basic framework for a free reward system to replace !freewaifu

main.py
Formerly stuff that was used in V marathon only, but it should get merged at some point.
=> August code updates

main.py
This should avoid confusion during/after the Black Friday sale
=> Show real spending on !packspending instead of estimate

bootstrapboostertemplate.htm, bootstraphandtemplate.htm, main.py, profiletemplate.html, trackertemplate.htm, website.js
Bet stuff, marathon tracker, etc
=> Updates done just before/during TCGMarathon

js/sets.js, templates/sets.ejs, waifus-bootstrap.css
- Sets now works better in mobile
- You can now search users in mobile again
- Since we only do one column on mobile, this will look slightly better.
=> Feat mobile 2019

main.py
Add waifu IDs to discord pullfeed channel(s) on drop, disenchant and promotion.
=> Add IDs to discord pullfeed

main.py
A lot of people prefer this help document and like to have it on hand.
=> Added command for the nepdoc link

main.py
=> Add config variables for schedule column indices

main.py
Seriously, i am stupid.
Signed-off-by: Marenthyu <petersilie93@live.de>
=> Actually push the Client-ID with requests to comply with Helix changes.

main.py
=> Make sure Client-ID is still a part of headers after a successful renewal

js/authcallback.js, js/core.js, main.py, package.json, sw.js, templates/includes/footer.ejs, templates/twitchauth.ejs, waifus-bootstrap.css, website.js
Not yet completed; Still need to handle the Push notifications better on the client side.
=> Push Notifications

main.py, templates/includes/footer.ejs
=> use correct base64 encoding method

main.py
=> freaking base64 in python

website.js
=> firefox apparently does not give an expiration time! Good to know

main.py
Squash or rebase merge this one so we don't keep getting merge commits kthx
=> Missed a minor but crucial change

main.py
=> Refer to correct images on trade

main.py, website.js
=> Properly delete subscriptions and use the correct Pythonic null

main.py
In practice all staff are asking permission before changing their godimages now anyway, so we may as well make it official. Staff can still insta approve their own requests if they see fit.
=> Remove godimage queue bypass for staff

main.py
=> "Why is this an Issue and not a PR?"

main.py
Figured this would be a nice QoL change.
Would allow people to input their times as XX:XX:XX:XXX in addition to XX:XX:XX.XXX
=> Allow using colon instead of period for bet times

main.py, templates/rules.ejs
=> Event cards

main.py
=> Properly use strings for new requests params

main.py
=> Pity counter

main.py
Added the missing check for empty counter
=> pity counter v2

main.py
Added missing cur check for pity counter
=> Added missing cur check for pity counter
